### ISSUE TITLE
FR: Multiple Views

### ISSUE THREAD

**Issue by chauser10** [Canna71/obsidian-sets#15]
Thank you for your work on this awesome plugin! 

Similar to shown in Anytype video at around [2:10](https://vimeo.com/717016770#t=130s) they show the ability to add multiple views to the same set in a tabbed view. 
To be more clear I have attached a screenshot highlighting the tabs I am after. ![image](https://github.com/Canna71/obsidian-sets/assets/22107538/80a097a9-e251-49a8-bcec-c7a0e555b2e3)

Regarding the `set` code block I would propose the following: 
````
```set
views:
 - name: Tab 1
   scope: ...
   fields: ...
   grid: ...
   filter: ...
   viewMode: gallery
   board:
     groupField: status
     lanes:
       - In Progress
 - name: Tab 2
   scope: ...
   fields: ...
   grid: ...
   filter: ...
   viewMode: grid
   board:
     groupField: status
     lanes:
       - In Progress
```
````

This preserves the current `set` code block syntax and also allows each view to be completely un-coupled from one another. In the example above Tab 1 and Tab 2 could have completely separate scopes.
