### ISSUE TITLE
feature: board view: ability to modify properties when moving between lanes

### ISSUE THREAD

**Issue by airtonix** [Canna71/obsidian-sets#24]
when moving between lanes, a board user would probably want certain fields to update.

obvious candidate is a board with `todo`, `in-progress` and `done`. We'd want to do something around tracking time.

```
scope:
  - vault
  - ""

timestamp: 1710885203291
filter:
  - ['type', 'eq', 'task']

viewMode: board

board:
  groupField: status
  lanes:
    - todo
    - in design
    - in progress
    - in review
    - done
  on:
    - event: 'lane_change'
      run: |
         if (lane_from === 'todo') {
           prop('time').push({ started: new Date() })
         }
         if (lane_to === 'todo' || lane_to === 'done') {
           prop('total', magicalSumOfTimeFieldFunction())
         }

```

if this can be done with computed properties in the archetype instead, then we should update the documentation to provide an obvious to follow example.
